### ISSUE TITLE
Error while uploading within CRG netwrok

### ISSUE THREAD

**Issue by rolivella** [proteomicsunitcrg/px-submission-tool#1]
Tested at 10.14.1.91 within CRG network and the FTP test is fine: 

![ftp1](https://user-images.githubusercontent.com/1679820/220891439-4364b06f-9d47-4d95-b2ed-dbf1b3470bbc.png)

![ftp2](https://user-images.githubusercontent.com/1679820/220891472-23bc7014-09e5-4400-bce8-8ee8f5298407.png)

The `config.props` is defined as: 

![config-props](https://user-images.githubusercontent.com/1679820/220891605-f9872a3e-1eeb-45e1-b41a-ecc98597cecb.png)

But when we upload the files we get this error log: 

```log
2023-02-22 11:47:00,587 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:121] IOException while uploading file: 2020MQ013_NIFI.pdResult
org.apache.commons.net.io.CopyStreamException: IOException caught while copying.
	at org.apache.commons.net.io.Util.copyStream(Util.java:136)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:117)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:27)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at org.apache.commons.net.io.SocketOutputStream.write(SocketOutputStream.java:71)
	at org.apache.commons.net.io.Util.copyStream(Util.java:124)
	... 8 common frames omitted
2023-02-22 11:47:00,588 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:124] CopyStreamException contains IOException: 
java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at org.apache.commons.net.io.SocketOutputStream.write(SocketOutputStream.java:71)
	at org.apache.commons.net.io.Util.copyStream(Util.java:124)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:117)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:27)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2023-02-22 11:47:00,588 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:126] Total byte transferred: 63971328
2023-02-22 11:47:00,588 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.net.SocketOutputStream.socketWrite0(Native Method)
2023-02-22 11:47:00,588 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.net.SocketOutputStream.socketWrite(Unknown Source)
2023-02-22 11:47:00,589 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.net.SocketOutputStream.write(Unknown Source)
2023-02-22 11:47:00,589 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] org.apache.commons.net.io.SocketOutputStream.write(SocketOutputStream.java:71)
2023-02-22 11:47:00,589 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] org.apache.commons.net.io.Util.copyStream(Util.java:124)
2023-02-22 11:47:00,589 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:117)
2023-02-22 11:47:00,589 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:27)
2023-02-22 11:47:00,589 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] javax.swing.SwingWorker$1.call(Unknown Source)
2023-02-22 11:47:00,590 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.util.concurrent.FutureTask.run(Unknown Source)
2023-02-22 11:47:00,590 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] javax.swing.SwingWorker.run(Unknown Source)
2023-02-22 11:47:00,590 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2023-02-22 11:47:00,590 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2023-02-22 11:47:00,590 ERROR [pool-1-thread-2] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.lang.Thread.run(Unknown Source)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:121] IOException while uploading file: 2020MQ013_NIFI_040_P10-4_01_1ug.raw
org.apache.commons.net.io.CopyStreamException: IOException caught while copying.
	at org.apache.commons.net.io.Util.copyStream(Util.java:136)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:117)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:27)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at org.apache.commons.net.io.SocketOutputStream.write(SocketOutputStream.java:71)
	at org.apache.commons.net.io.Util.copyStream(Util.java:124)
	... 8 common frames omitted
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:124] CopyStreamException contains IOException: 
java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at org.apache.commons.net.io.SocketOutputStream.write(SocketOutputStream.java:71)
	at org.apache.commons.net.io.Util.copyStream(Util.java:124)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:117)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:27)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:126] Total byte transferred: 64339968
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.net.SocketOutputStream.socketWrite0(Native Method)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.net.SocketOutputStream.socketWrite(Unknown Source)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.net.SocketOutputStream.write(Unknown Source)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] org.apache.commons.net.io.SocketOutputStream.write(SocketOutputStream.java:71)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] org.apache.commons.net.io.Util.copyStream(Util.java:124)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:117)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:27)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] javax.swing.SwingWorker$1.call(Unknown Source)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.util.concurrent.FutureTask.run(Unknown Source)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] javax.swing.SwingWorker.run(Unknown Source)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2023-02-22 11:47:02,365 ERROR [pool-1-thread-3] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.lang.Thread.run(Unknown Source)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:121] IOException while uploading file: 2020MQ013_NIFI_025_P7-1_01_1ug.raw
org.apache.commons.net.io.CopyStreamException: IOException caught while copying.
	at org.apache.commons.net.io.Util.copyStream(Util.java:136)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:117)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:27)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at org.apache.commons.net.io.SocketOutputStream.write(SocketOutputStream.java:71)
	at org.apache.commons.net.io.Util.copyStream(Util.java:124)
	... 8 common frames omitted
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:124] CopyStreamException contains IOException: 
java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at org.apache.commons.net.io.SocketOutputStream.write(SocketOutputStream.java:71)
	at org.apache.commons.net.io.Util.copyStream(Util.java:124)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:117)
	at uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:27)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:126] Total byte transferred: 64411648
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.net.SocketOutputStream.socketWrite0(Native Method)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.net.SocketOutputStream.socketWrite(Unknown Source)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.net.SocketOutputStream.write(Unknown Source)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] org.apache.commons.net.io.SocketOutputStream.write(SocketOutputStream.java:71)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] org.apache.commons.net.io.Util.copyStream(Util.java:124)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:117)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] uk.ac.ebi.pride.gui.task.FileFTPUploadTask.doInBackground(FileFTPUploadTask.java:27)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] javax.swing.SwingWorker$1.call(Unknown Source)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.util.concurrent.FutureTask.run(Unknown Source)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] javax.swing.SwingWorker.run(Unknown Source)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2023-02-22 11:47:03,458 ERROR [pool-1-thread-4] u.a.e.p.g.t.FileFTPUploadTask [FileFTPUploadTask.java:131] java.lang.Thread.run(Unknown Source)
```

**Comment by rolivella** [comment]
Firewall rules for .91 at CRG network level (Isma): 

> Les 10.44.* funcionen per defecte i les 10.14 .* funcionen pq existeix una regla especifica per a que sigui aixi:
> ![rule](https://user-images.githubusercontent.com/1679820/222096486-fb4e5378-0af5-4fa6-8dfa-16f76a49bf44.jpg)

**Comment by rolivella** [comment]
I was able to upload the dataset from: Ubuntu 22.04 10.44.128.77

**Comment by rolivella** [comment]
Pending test with Eduardo from 91
